name: Update packages

on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - main
  schedule:
    - cron: 0 */12 * * *
  watch:
    types: started

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    name: Update ${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        target: [packages]
        
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: 安装环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install git subversion git-core wget
        sudo timedatectl set-timezone "$TZ"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
    - name: Clone packages
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x ${{matrix.target}}.sh
        git clone https://github.com/xiexiaosheng/openwrt-package.git ${{matrix.target}}
        cd ${{matrix.target}}
        rm -Rf *
        git rm --cache *
        $GITHUB_WORKSPACE/${{matrix.target}}.sh

    - name: Upload
      run: |
        [ -e $GITHUB_WORKSPACE/README.md ] && cp $GITHUB_WORKSPACE/README.md $GITHUB_WORKSPACE/${{matrix.target}}
        cd $GITHUB_WORKSPACE/${{matrix.target}}
        git add .
        git commit -m "update$(TZ='Asia/Shanghai' date +@%Y%m%d)"
        git push --quiet "https://${{ secrets.TOKEN }}@github.com/xiexiaosheng/openwrt-package.git" HEAD:main || exit 0

    - name: 清理Actions空间
      if: env.REPO_TOKEN
      uses: Mattraks/delete-workflow-runs@main
      with:
          token: ${{ secrets.REPO_TOKEN }}
          repository: ${{ github.repository }}
          keep_minimum_runs: 0
          retain_days: 1